# Generated by Django 4.0.3 on 2022-04-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0002_rename_seller_info_buyerinfo_houseinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='buyproperty.buyerinfo'),
        ),
        migrations.AlterField(
            model_name='houseinfoimage',
            name='house_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='buyproperty.houseinfo'),
        ),
    ]
