# Generated by Django 4.0.3 on 2022-04-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0004_rename_houseinfo_wishedhouseinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishedHouseInfo',
            new_name='WishHouseInfo',
        ),
    ]
