# Generated by Django 4.0.3 on 2022-05-03 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyproperty', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('descrption', models.TextField()),
                ('location', models.CharField(max_length=250)),
                ('land_area', models.FloatField(blank=True, null=True)),
                ('floor_area', models.FloatField(blank=True, null=True)),
                ('bedroom', models.IntegerField(blank=True, null=True)),
                ('bathroom', models.IntegerField(blank=True, null=True)),
                ('livingroom', models.IntegerField(blank=True, null=True)),
                ('kitchen', models.IntegerField(blank=True, null=True)),
                ('room_details', models.TextField(blank=True, null=True)),
                ('furnished_condition', models.CharField(blank=True, max_length=250, null=True)),
                ('built_year', models.DateField(blank=True, null=True)),
                ('parking_sapce', models.CharField(blank=True, max_length=300, null=True)),
                ('garden', models.CharField(blank=True, max_length=10, null=True)),
                ('house_facing', models.CharField(blank=True, max_length=300, null=True)),
                ('road_size', models.FloatField(blank=True, null=True)),
                ('road_condition', models.CharField(blank=True, max_length=250, null=True)),
                ('water_facilities', models.CharField(blank=True, max_length=250, null=True)),
                ('sewage_facilties', models.CharField(blank=True, max_length=250, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_for', models.IntegerField(choices=[(1, 'Sale'), (2, 'Buy'), (3, 'To Rent'), (4, 'For Rent')], default=1)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='wishhouseinfo',
            name='buyer',
        ),
        migrations.RenameModel(
            old_name='HouseInfoImage',
            new_name='HouseImage',
        ),
        migrations.DeleteModel(
            name='BuyerInfo',
        ),
        migrations.AlterField(
            model_name='comment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_comments', to='buyproperty.house'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='house_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='buyproperty.house'),
        ),
        migrations.DeleteModel(
            name='WishHouseInfo',
        ),
    ]
