# Generated by Django 4.0.3 on 2022-05-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyproperty', '0007_house_remove_wishhouseinfo_buyer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseimage',
            old_name='house_info',
            new_name='house',
        ),
    ]
