# Generated by Django 4.0.3 on 2022-04-27 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellproperty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseInfoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_picture')),
                ('house_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellproperty.houseinfo')),
            ],
        ),
    ]
