# Generated by Django 4.0.3 on 2022-04-27 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellproperty', '0002_houseinfoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='sellproperty.sellerinfo'),
        ),
        migrations.AlterField(
            model_name='houseinfoimage',
            name='house_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='sellproperty.houseinfo'),
        ),
    ]
