# Generated by Django 4.0.3 on 2022-05-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellproperty', '0003_alter_houseinfo_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseinfoimage',
            name='house_info',
        ),
        migrations.DeleteModel(
            name='HouseInfo',
        ),
        migrations.DeleteModel(
            name='HouseInfoImage',
        ),
        migrations.DeleteModel(
            name='SellerInfo',
        ),
    ]
