# Generated by Django 4.0.3 on 2022-05-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentproperty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renthouseinfo',
            name='buyer',
        ),
        migrations.DeleteModel(
            name='HouseInfoImage',
        ),
        migrations.DeleteModel(
            name='LessorInfo',
        ),
        migrations.DeleteModel(
            name='RentHouseInfo',
        ),
    ]
