# Generated by Django 4.0.3 on 2022-05-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nijiuser',
            name='address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nijiuser',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nijiuser',
            name='is_lessee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nijiuser',
            name='is_lessor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nijiuser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nijiuser',
            name='landmark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='nijiuser',
            name='phone',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
